### ISSUE TITLE
How to manage Shopify cart object in js after rendered website fully?

### ISSUE THREAD

**Issue by jldev1** [jinlingdev/shopping-cart-built#1]
Hello, I am getting some problems with shopping cart.
When the page is fully loaded, I am facing some issues with cart object management. I am using native shopify jquery ajax for that. is there any way to manage and add/update/remove cart items on JavaScript?
Thanks.

**Comment by jamescalison** [comment]
Hello there, 
Check [cart.js](https://cartjs.org/)
cart.js would be helpful for you.

**Comment by jldev1** [comment]
Hi James, thanks for sharing that url, I will check it.

**Comment by jldev1** [comment]
It's working! thanks so much!!!

**Comment by jamescalison** [comment]
I am glad to hear that is working for you. :)
